experiment:
  name: "demo_experiment"
  tracking_uri: "file:./mlruns"

dataset:
  raw_path: "path_of_raw_data"
  processed_path: "path_of_preprocessed_data"
  target: "target_colum_name"
  test_size: 0.2
  random_state: 42

model:
  type: "model_name"

params:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8

training:
  early_stopping_rounds: 10
